### ISSUE TITLE
[Error] Vote aggregation error 

### ISSUE THREAD

**Issue by thomasrannou** [HugoGresse/open-feedback#1477]
For this event : https://openfeedback.io/Buf9m89UOSzTwTOzKwGT/0
Noemie Delrue's talk page is not loading : https://openfeedback.io/Buf9m89UOSzTwTOzKwGT/0/Q6kvEiDyzAYtvzxTN48M
The others are all ok except this one specifically.

The error below :
Something went wrong. It may be linked to an issue with Open Feedback itself or your internet connection.
An alert has been triggered and someone will hopefully fix this soon (I think it is me)

TypeError: Cannot read properties of undefined (reading 'toDate')
The error may be correlated with this previous error:
TypeError: Cannot read properties of undefined (reading 'toDate')
    at https://openfeedback.io/static/js/main.053dc3f1.js:2:1208518
    at Array.forEach (<anonymous>)
    at https://openfeedback.io/static/js/main.053dc3f1.js:2:1208354
    at Array.forEach (<anonymous>)
    at https://openfeedback.io/static/js/main.053dc3f1.js:2:1208252
    at https://openfeedback.io/static/js/main.053dc3f1.js:2:1123076
    at d (https://openfeedback.io/static/js/main.053dc3f1.js:2:1122025)
    at https://openfeedback.io/static/js/main.053dc3f1.js:2:1123209
    at d (https://openfeedback.io/static/js/main.053dc3f1.js:2:1122025)
    at Object.current (https://openfeedback.io/static/js/main.053dc3f1.js:2:1208845)

Thanks

**Comment by HugoGresse** [comment]
I've fixed the issue in production for this specific talk, but the error may still happen on another event. 

I believe what happen was: 
1. User added a text vote 
2. Someone upvoted it
3. The user from 1. deleted it 
4. The vote stay display

Deleting this solve the issue : 
![image](https://user-images.githubusercontent.com/662377/198391442-081c4be8-778a-46c2-ae4e-d478f8c214e3.png)
