### ISSUE TITLE
Display full dates in Event Mode

### ISSUE THREAD

**Issue by tpoindessous** [HugoGresse/open-feedback#1588]
Hi !

First, thanks for your work !

![Capture d’écran 2024-01-23 à 12 37 31](https://github.com/HugoGresse/open-feedback/assets/3054608/ddf59cce-9c42-4c8c-b662-ab5fb97eae87)

We use OpenFeedback for recurrent events. We created only one event and we add each week, one new presentation.

We would like, please, see the dates in "full date" mode : maybe "mardi 23 Janvier" or in iso mode ? 

Thanks.

**Comment by HugoGresse** [comment]
This seems easy to do!

**Comment by HugoGresse** [comment]
@tpoindessous does the linked PR suits your needs? 

Also, thanks for your sponsorship !!

**Comment by tpoindessous** [comment]
Yes, thanks, I would be very happy to have this 

Have a nice day !

**Comment by HugoGresse** [comment]
Done and deployed!
