### ISSUE TITLE
[Feedback] Persistent stickers position

### ISSUE THREAD

**Issue by martinbonnin** [HugoGresse/open-feedback#418]
<img width="232" alt="Capture d’écran 2020-02-09 à 13 05 17" src="https://user-images.githubusercontent.com/3974977/74101686-dca2d000-4b3c-11ea-82d0-51b59621ce69.png">

When voting on a talk, the sticker appears at a random position. It would be nice if the position was saved and restored :)

**Comment by HugoGresse** [comment]
it's a good idea but seems to be a lot of work (votes are aggregated from /userVotes to /sessionsVotes. 
I'm planning this for the "vNext" which will come someday after the first v1 release.

**Comment by HugoGresse** [comment]
Closing this, this is too much work a little user value 😅

**Comment by martinbonnin** [comment]
Also, it adds some element of surprise so it could be argued that it's a feature ;)

**Comment by HugoGresse** [comment]
what we could do it having specific chip colors for user but this breaks the anonymity  🤔
