### ISSUE TITLE
Localized vote labels

### ISSUE THREAD

**Issue by martinbonnin** [HugoGresse/open-feedback#420]
Currently, the vote labels can only take one value. If someone visits the website with a browser configured for e.g. English and the votes were setup in French, he/she will see a french label. 

It would be nice to be able to have keys for different votes that could be translated into different values.

**Comment by HugoGresse** [comment]
Design : https://www.figma.com/proto/EivIdkyPELnGs416ND0C2bWG/Open-feedback?node-id=92%3A675&viewport=833%2C-3192%2C0.8411473631858826&scaling=min-zoom

Planned to be dev next week.
