### ISSUE TITLE
[Admin] Shed support? 

### ISSUE THREAD

**Issue by HugoGresse** [HugoGresse/open-feedback#426]
Some events are using shed.com for the agenda/schedule/speaker. 
It could be great to to support it. 
Attached is the export of the API answer of Shed. 
[Archive.zip](https://github.com/HugoGresse/open-feedback/files/4179835/Archive.zip)

**Comment by lchenay** [comment]
Shed.com seems dead, is this still needed?

**Comment by HugoGresse** [comment]
Indeed, not needed! Probably worth investigating for Sessionize though.
